# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
# Define services
services:
  weather:
    image: "airbnski/weather"
    ports:
      - "8081:8081"
    restart: always
  resort:
    image: "airbnski/resort"
    ports:
      - "8082:8082"
    restart: always
    depends_on:
        - weather
  ui:
    image: "airbnski/ui"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - resort
