# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

# Define services
services:
  # Microservice
  weather:
    # Configuration for building the docker image for the backend service
    image: "airbnski/weather"
    ports:
      - "8081:8081"
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  resort:
    # Configuration for building the docker image for the backend service
    image: "airbnski/resort"
    ports:
      - "8082:8082"
    restart: always
    depends_on:
        - weather
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend    
      - frontend    

  # Frontend Service 
  ui:
    image: "airbnski/ui"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - weather
    networks:
      - frontend  

        # Networks to be created to facilitate communication between containers
networks:
    backend:
    frontend:
