openapi: 3.0.0
info:
  title: AirbnSki Resort API
  description: >-
    This is the API Documentation of the AirbnSki Resort API.
  contact:
    email: operations@airbnski.com
  version: 1.0.0 beta - subject to change
paths:
  '/api/v1/resorts':
    summary: Resorts API Endpoint
    description: Resorts
    get:
      summary: Get list of resorts
      operationId: get-resorts
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SkiResort'
          description: Successful operation
      tags:
        - Resort
  '/api/v1/resorts/{resortId}':
    summary: Detailed information about the resort with specified ID
    description: Detailed information about resort
    parameters:
      - name: resortId
        in: path
        description: ID of the resort
        required: true
        schema:
          type: integer
          format: int32
    get:
      summary: Get Resort details
      operationId: get-resort
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkiResort'
          description: Successful operation
        '404':
          description: Resort not found
      tags:
        - Resort
        
components:
  schemas:
    SkiResort:
      type: object
      required:
        - skiResortId
        - name
        - isOpen
      properties:
        skiResortId:
          type: integer
          description: Ski resort id
        name:
          type: string
          example: 'Laax Ski resort'
        isOpen:
          type: boolean
          example: true
